version: '3'
services:
  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:latest"
    networks:
      - selenoid-network
    volumes:
      - "./selenoid/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/logs:/opt/selenoid/logs"
      - "./selenoid/video:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid-network", "-limit", "10"]
    ports:
      - "4445:4444"
  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:latest"
    links:
      - selenoid
    networks:
      - selenoid-network
    command: ["--selenoid-uri", "http://selenoid:4444"]
    ports:
      - "8081:8080"
networks:
  selenoid-network:
    external:
      name: selenoid-network