name: gauge-test
on: [push]
jobs:
  gauge-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: curl https://get.docker.com | sh
      - run: docker --version
      - run: curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - run: docker-compose --version
      - run: curl -SsL https://downloads.gauge.org/stable | sh -s -- --location-[custom path]
      - run: gauge install java --version 0.7.15
      - run: gauge version
      - run: mvn test